= Rustlio
:docs: https://docs.rs/rustlio/latest/rustlio/
:license: http://www.opensource.org/licenses/mit-license.html
:repo: https://github.com/settermjd/rustlio
:rust-install: https://doc.rust-lang.org/cargo/getting-started/installation.html
:try-twilio: https://twilio.com/try-twilio

This crate simplifies interacting with Twilio's APIs in Rust applications.

At this point, it's not a comprehensive library, but does provide the basics.
My intention is to provide (yet another) Rust library to make interacting with Twilio's
APIs as easy as possible, and to give me a project to continue learning Rust.

== Prerequisites

You'll need the following to use the application:

* A Twilio account (free or paid).
{try-twilio}[Create an account] if you don't already have one.
* Rust (1.85 or above) and Cargo (1.94 or above).
{rust-install}[Follow the installation instructions] if you haven't installed them yet.
* Git
* Your preferred code editor or IDE, such as neovim or Visual Studio Code
* Some terminal experience is helpful, though not required

== Quick Start

To get started using the library, add it to your project by running the command below:

[,bash]
----
cargo add rustlio
----

== Using the library

You can find out how to use the library in {docs}[its documentation].

== Contributing

If you want to contribute to the project, whether you have found issues with it or just want to improve it, here's how:

* {repo}/issues[Issues]: ask questions and submit your feature requests, bug reports, etc
* {repo}/pulls[Pull requests]: send your improvements

== License

{license}[MIT]

== Disclaimer

No warranty expressed or implied.
Software is as is.
